# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20160914_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='BusAlimentador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.BusAlimentador'),
        ),
        migrations.AlterField(
            model_name='tiempoasignacion',
            name='BusAlimentador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.BusAlimentador'),
        ),
    ]
