# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20160914_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despacho',
            old_name='BusAlimentador',
            new_name='NumeroBus',
        ),
        migrations.RenameField(
            model_name='tiempoasignacion',
            old_name='BusAlimentador',
            new_name='NumeroBus',
        ),
    ]
