# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20160914_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='NumeroBus',
            field=models.ForeignKey(blank=True, default=800, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.BusAlimentador'),
        ),        
    ]
