# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20160914_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempoasignacion',
            name='NumeroBus',
        ),
    ]
