# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20160914_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='CodRuta',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='NumeroBus',
        ),
        migrations.DeleteModel(
            name='Despacho',
        ),
    ]
