# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusAlimentador',
            fields=[
                ('NumeroBus', models.IntegerField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(blank=True, max_length=45, null=True)),
                ('CapacidadBus', models.IntegerField()),
                ('NumDespacho', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['NumeroBus'],
                'db_table': 'BusAlimentador',
                'verbose_name_plural': 'BusAlimentador',
            },
        ),
        migrations.CreateModel(
            name='BusesDisponibles',
            fields=[
                ('IdDisponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('Disponibilidad', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('TiempoEspera', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BusesDisponibles',
                'verbose_name_plural': 'BusesDisponibles',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('NumDespacho', models.AutoField(primary_key=True, serialize=False)),
                ('FechaDespacho', models.DateField()),
                ('HoraDespacho', models.TimeField()),
                ('HoraLlegada', models.TimeField(blank=True, null=True)),
                ('Delay', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('FactorConfiabilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('CargaPasajeros', models.IntegerField()),
                ('Frecuencia', models.TimeField()),
                ('HoraLlegadaEsperada', models.CharField(max_length=45)),
                ('Tope', models.IntegerField()),
            ],
            options={
                'db_table': 'Despacho',
                'verbose_name_plural': 'Despacho',
            },
        ),
        migrations.CreateModel(
            name='HorarioOperador',
            fields=[
                ('TipoHorario', models.IntegerField(primary_key=True, serialize=False)),
                ('Jornada', models.CharField(max_length=45)),
                ('TipoDia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'HorarioOperador',
                'verbose_name_plural': 'HorarioOperador',
            },
        ),
        migrations.CreateModel(
            name='HorarioRecorrido',
            fields=[
                ('CodFranja', models.IntegerField(primary_key=True, serialize=False)),
                ('HoraInicio', models.TimeField()),
                ('HoraFin', models.TimeField()),
                ('TiempoEstimado', models.TimeField()),
                ('Franja', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['CodFranja'],
                'db_table': 'HorarioRecorrido',
                'verbose_name_plural': 'HorarioRecorrido',
            },
        ),
        migrations.CreateModel(
            name='ListaDias',
            fields=[
                ('CodDia', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
            ],
            options={
                'ordering': ['CodDia'],
                'db_table': 'ListaDias',
                'verbose_name_plural': 'ListaDias',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('DocOperador', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=45)),
                ('Apellidos', models.CharField(max_length=45)),
                ('Perfil', models.CharField(max_length=45)),
                ('Clave', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('CodOrigen', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreOrigen', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['CodOrigen'],
                'db_table': 'Origen',
                'verbose_name_plural': 'Origen',
            },
        ),
        migrations.CreateModel(
            name='RutaAlimentadora',
            fields=[
                ('CodRuta', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreRuta', models.CharField(max_length=45)),
                ('Area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UltimoDespacho', models.TimeField(blank=True, null=True)),
                ('CodOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Origen')),
            ],
            options={
                'ordering': ['CodRuta'],
                'db_table': 'RutaAlimentadora',
                'verbose_name_plural': 'RutaAlimentadora',
            },
        ),
        migrations.CreateModel(
            name='TiempoAsignacion',
            fields=[
                ('NumSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('TiempoEspera', models.TimeField(blank=True, null=True)),
                ('Despachado', models.IntegerField(default=0)),
                ('CodRuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.RutaAlimentadora')),
                ('NumeroBus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.BusAlimentador')),
            ],
            options={
                'ordering': ['NumSolicitud'],
                'db_table': 'TiempoAsignacion',
                'verbose_name_plural': 'TiempoAsignacion',
            },
        ),
        migrations.CreateModel(
            name='TipoDia',
            fields=[
                ('TipoDia', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreTipoDia', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['TipoDia'],
                'db_table': 'TipoDia',
                'verbose_name_plural': 'TipoDia',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('NumAcceso', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=45)),
                ('FechaAcceso', models.DateField()),
                ('HoraAcceso', models.TimeField()),
                ('PasajerosEspera', models.IntegerField()),
                ('DensidadPasajeros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CodRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.RutaAlimentadora')),
            ],
            options={
                'ordering': ['NumAcceso'],
                'db_table': 'Usuario',
                'verbose_name_plural': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='operador',
            name='CodOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Origen'),
        ),
        migrations.AddField(
            model_name='operador',
            name='TipoHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.HorarioOperador'),
        ),
        migrations.AddField(
            model_name='listadias',
            name='TipoDia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.TipoDia'),
        ),
        migrations.AddField(
            model_name='horariorecorrido',
            name='CodRuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.RutaAlimentadora'),
        ),
        migrations.AddField(
            model_name='horariorecorrido',
            name='TipoDia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.TipoDia'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='CodRuta',
            field=models.ForeignKey(default=81, on_delete=django.db.models.deletion.CASCADE, to='sistema.RutaAlimentadora'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='NumeroBus',
            field=models.ForeignKey(default=800, on_delete=django.db.models.deletion.CASCADE, to='sistema.BusAlimentador'),
        ),
        migrations.AddField(
            model_name='busesdisponibles',
            name='CodOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Origen'),
        ),
        migrations.AddField(
            model_name='busalimentador',
            name='CodRuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.RutaAlimentadora'),
        ),
    ]
