# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='CodRuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.RutaAlimentadora'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='Delay',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='NumeroBus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.BusAlimentador'),
        ),
    ]
