# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20160930_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='HoraLlegadaEsperada',
            field=models.TimeField(max_length=45),
        ),
    ]
