# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20160930_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busesdisponibles',
            name='CodOrigen',
        ),
        migrations.DeleteModel(
            name='BusesDisponibles',
        ),
    ]
