# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20161010_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='TipoHorario',
        ),
        migrations.DeleteModel(
            name='HorarioOperador',
        ),
    ]
